// Application Constants

export const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB in bytes
export const ALLOWED_FILE_TYPES = ['application/pdf']
export const SESSION_TIMEOUT = 30 * 60 * 1000 // 30 minutes in milliseconds

// Acceptance Requirements Deadlines (in working days)
export const ADMIN_REVIEW_DEADLINE_DAYS = 14 // Admin must review within 14 working days
export const REVISION_DEADLINE_DAYS = 14 // Applicant must resubmit within 14 working days

export const APPLICATION_STEPS = {
  PERMIT_TYPE: 1,
  PROJECT_COORDINATES: 2,    // Must be approved before continuing
  PROJECT_INFO: 3,
  PROPONENT_INFO: 4,
  PROJECT_DETAILS: 5,
  ACCEPTANCE_DOCS: 6,
  OTHER_REQUIREMENTS: 7,
  REVIEW: 8,
} as const

// Total steps in the application wizard
export const TOTAL_WIZARD_STEPS = 8

export const DOCUMENT_REQUIREMENTS = {
  ISAG: {
    acceptance: [
      'APPLICATION_FORM',
      'SURVEY_PLAN',
      'LOCATION_MAP',
      'WORK_PROGRAM',
      'IEE_REPORT',
      'EPEP',
      'PROOF_TECHNICAL_COMPETENCE',
      'PROOF_FINANCIAL_CAPABILITY',
      'ARTICLES_INCORPORATION',
      'OTHER_SUPPORTING_PAPERS',
    ],
    other: [
      'AREA_STATUS_CLEARANCE_CENRO',
      'AREA_STATUS_CLEARANCE_MGB',
      'CERTIFICATE_POSTING_BARANGAY',
      'CERTIFICATE_POSTING_MUNICIPAL',
      'CERTIFICATE_POSTING_PROVINCIAL',
      'CERTIFICATE_POSTING_CENRO',
      'CERTIFICATE_POSTING_PENRO',
      'CERTIFICATE_POSTING_MGB',
      'ECC',
      'SANGGUNIAN_ENDORSEMENT_BARANGAY',
      'SANGGUNIAN_ENDORSEMENT_MUNICIPAL',
      'SANGGUNIAN_ENDORSEMENT_PROVINCIAL',
      'FIELD_VERIFICATION_REPORT',
      'SURETY_BOND',
    ],
  },
  CSAG: {
    acceptance: [
      'APPLICATION_FORM',
      'SURVEY_PLAN',
      'LOCATION_MAP',
      'WORK_PROGRAM',
      'IEE_REPORT',
      'PROOF_TECHNICAL_COMPETENCE',
      'PROOF_FINANCIAL_CAPABILITY',
      'ARTICLES_INCORPORATION',
      'OTHER_SUPPORTING_PAPERS',
    ],
    other: [
      'AREA_STATUS_CLEARANCE_CENRO',
      'AREA_STATUS_CLEARANCE_MGB',
      'CERTIFICATE_POSTING_BARANGAY',
      'CERTIFICATE_POSTING_MUNICIPAL',
      'CERTIFICATE_POSTING_PROVINCIAL',
      'CERTIFICATE_POSTING_CENRO',
      'CERTIFICATE_POSTING_PENRO',
      'CERTIFICATE_POSTING_MGB',
      'ECC',
      'SANGGUNIAN_ENDORSEMENT_BARANGAY',
      'SANGGUNIAN_ENDORSEMENT_MUNICIPAL',
      'SANGGUNIAN_ENDORSEMENT_PROVINCIAL',
      'FIELD_VERIFICATION_REPORT',
      'SURETY_BOND',
    ],
  },
} as const

export const SURETY_BOND_AMOUNT = 20000 // PHP 20,000

